const classRoomType = {
  GET_CLASS_SUCCESS: 'GET_CLASS_SUCCESS',
  FILTER_CLASS: 'FILTER_CLASS',
  FIND_CLASS: 'FIND_CLASS',
  CREATE_CLASS: 'CREATE_CLASS',
  UPDATE_CLASS: 'UPDATE_CLASS',
  DELETE_CLASS: 'DELETE_CLASS',
  DUPLICATE_CLASS: 'DUPLICATE_CLASS',
};
export default classRoomType;
