const classGroupType = {
  GET_CLASS_GROUP: 'GET_CLASS_GROUP',
  CREATE_CLASS_GROUP: 'CREATE_CLASS_GROUP',
  UPDATE_CLASS_GROUP: 'UPDATE_CLASS_GROUP',
  DELETE_CLASS_GROUP: 'DELETE_CLASS_GROUP',
};

export default classGroupType;
